base_dir: "/Users/fyk7/python-projects/ml/commonlit-36th-place"
# base_dir: "/content/drive/MyDrive/kaggle/commonlit_readability"
job_name: 'roberta-base-demo'
model_class: 'LitModel'
model_path: "roberta-base"
tokenizer_path: "roberta-base"
batch_size: 8
max_len: 256
epochs: 3
nfolds: 5
fold_name: "Fold_stratified_url"
seed: 1000


# ログの出力先のディレクトリ名を変更(実行時引数を結合)
hydra:
  run:
    dir: output/${hydra.job.name}/${hydra.job.override_dirname}
    # colabで実行する場合はGoogle Driveをマウントして以下のディレクトリを指定する
    # dir: /content/drive/MyDrive/kaggle/commonlit_readability/outputs/${hydra.job.override_dirname}


defaults:
  - _self_
  - optimizer: base