base_dir: "/Users/fyk7/python-projects/ml/commonlit-36th-place"
# base_dir: "/content/drive/MyDrive/kaggle/commonlit_readability"
job_name: 'roberta-base-demo'
model_class: 'LitModel'
model_path: "roberta-base"
tokenizer_path: "roberta-base"
optimizer:
  atten_param_start: 199
  regressor_param_start: 203
  atten_lr: "1e-4"
  reg_lr: "1e-4"
  bert_mid_level_layer_start: 69
  bert_high_level_layer_start: 133
  bert_low_layer_lr: "1e-5"
  bert_mid_layer_lr: "2e-5"
  bert_high_layer_lr: "2e-5"
batch_size: 8
max_len: 256
epochs: 3
nfolds: 5
seed: 1000

# TODO local実行とcolab実行を切り分ける
# TODO google driveに直接outputするためのパスを考える
# hydra:
#   run:
#     dir: "/content/drive/MyDrive/kaggle/commonlit_readability/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}"


defaults:
  - _self_
  - dataset: large